# Generated by Django 5.0 on 2023-12-19 21:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
