# Generated by Django 5.0 on 2023-12-21 22:06

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('objManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
